title: The Open Source Guide
description: The unraveling of open source mystery
theme: jekyll-theme-cayman
show_downloads: false

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
